# Generated by Django 5.1.1 on 2024-09-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True,
                                          verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('image',
                 models.ImageField(blank=True, upload_to='static/images/',
                                   verbose_name='Фото')),
                ('password',
                 models.CharField(max_length=255, verbose_name='Пароль')),
                ('phone',
                 models.CharField(max_length=255, verbose_name='№ телефона')),
                ('email', models.EmailField(max_length=255,
                                            verbose_name='Электронная почта')),
                ('nickname_tg', models.CharField(blank=True, max_length=255,
                                                 verbose_name='Никнейм Telegram')),
                ('nickname_inst', models.CharField(blank=True, max_length=255,
                                                   verbose_name='Никнейм Instagram')),
                ('group_number',
                 models.CharField(max_length=255, verbose_name='№ группы')),
                ('balance', models.IntegerField(default=0,
                                                verbose_name='Количество баллов')),
                ('status',
                 models.CharField(max_length=100, verbose_name='Статус')),
                ('service',
                 models.CharField(max_length=255, verbose_name='Пакет услуг')),
                ('internship',
                 models.CharField(max_length=255, verbose_name='Стажировка')),
                ('level', models.ForeignKey(blank=True,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            to='student.level',
                                            verbose_name='Уровень доступа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
